### ISSUE TITLE
java version 19 error at `./gradlew installDist --stacktrace`

### ISSUE THREAD

**Issue by kirankotari** [dev-jan/wifi-qrcode-generator#2]
I am using following Java version
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment Homebrew (build 19)
OpenJDK 64-Bit Server VM Homebrew (build 19, mixed mode, sharing)

OS: Mac

```
java.lang.IllegalArgumentException: Could not determine java version from '19'.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:64)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:73)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by dev-jan** [comment]
Hi @kirankotari 

Thanks for using my little wifi tool!

To your issue: The reason of this error is, that Gradle (the build environment that is used) does not yet support Java 19 or 20 (see https://docs.gradle.org/current/userguide/compatibility.html). But I updated the used gradle version of this project to the newest one, so at least the newest java LTS version is now supported (Java 18). Can you try it again with java 18?

**Comment by kirankotari** [comment]
@dev-jan Thanks for your response, I have downgraded the java it's fine now.
